### ISSUE TITLE
colab notebook needs to pip install stanza

### ISSUE THREAD

**Issue by KentonMurray** [hltcoe/patapsco#55]
Cannot run notebook without first installing stanza

**Comment by KentonMurray** [comment]
Submitted PR: https://github.com/hltcoe/patapsco/pull/56

**Comment by KentonMurray** [comment]
Actually, I see stanza dependency in the environment.yml file.

I'm not sure why this was still throwing an error in google colab. My pr will fix that, but it seems like this is maybe not the right solution.

**Comment by cash** [comment]
Thanks, @KentonMurray, for this. @eugene-yang can you take a look at this?

**Comment by eugene-yang** [comment]
Sorry for the delay. 
I tested on Google Colab and doesn't seem to have any problem. 
@KentonMurray how were you running the notebook?

**Comment by KentonMurray** [comment]
I was running this on Google Colab. I haven't been able to reproduce this issue anymore. I wonder if it was a colab one-off issue...
